monolog:
    handlers:
        request:
            type: stream
            path: "%kernel.logs_dir%/requetes.log"
            level: error
            channels: request
            bubble: false
        important:
            type: stream
            path: "%kernel.logs_dir%/important.log"
            level: error
            bubble: false
        secondaire:
            type: stream
            path: "%kernel.logs_dir%/secondaire.log"
            level: debug
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
